# Agent & maintainer guide ({{PROJECT_TITLE}})

**Single source of truth** for humans and AI agents. Platform-specific files only point here — they do not duplicate rules.

**Active tools (this repo):** {{WORKFLOW_TOOLS_LIST}}

| Platform | Official instruction file | Role in this repo |
|----------|---------------------------|-------------------|
| **All / Codex** | `AGENTS.md` | **Canonical** — full workflow (this file) |
| **Cursor** | `AGENTS.md` + `.cursor/rules/*.mdc` | Rules mirror triage with `alwaysApply: true` |
| **Antigravity** | `.agents/rules/*.md` | Rules mirror triage with `trigger: always_on` |
| **Claude Code** | `CLAUDE.md` | Stub → read `AGENTS.md` |
| **Gemini CLI** | `AGENTS.md` (+ optional `GEMINI.md`) | Auto-discovered; stub optional |

See `docs/agent-platforms.md` for official doc links.

## Git & deploy

{{GIT_DEPLOY_SECTION}}

## Changelog (`CHANGELOG.md`)

- **`## [Unreleased]`** — user-relevant changes on integration branch.
- Version blocks — what shipped on **`{{PRODUCTION_BRANCH}}`**.
- Use `### Added` / `### Changed` / `### Fixed` / `### Removed`.

## Issue triage & delivery (AI default)

When the user describes a **feature**, **bug**, or **improvement**, **automatically triage** unless they skip or name `#N`.

### Phase 1 — Triage (no coding)

1. Investigate codebase (read-only).
2. `gh issue list --repo {{GH_REPO}} --state open --search "…"`
3. If duplicate → link it; do not create another.
4. New issue via `./scripts/gh-triage-issue.sh`:
   - Title: `[Bug]:` / `[Feature]:`
   - Body: use `templates/issue-body.example.md` structure — must include `## Acceptance criteria` with `- [ ]` lines
   - Labels: `bug` / `enhancement`; `priority:high|medium|low`; `client-facing` if user-visible
5. Add to project board; reply with URL; **stop**.

End with: *"Review the issue; tell me which # to implement first."*

### Phase 2 — Implement

Triggers: *Implement #N*, *kerjakan #N*, *LGTM #N*.

- Follow acceptance criteria; PR `Fixes #N`; commit only when asked.

### Phase 3 — Close-out

Triggers: user confirms *works* / *ok* / *sudah work* for **#N**.

1. Verify AC against code/commits.
2. `./scripts/gh-close-verified-issue.sh N --comment-file …`

### Skip triage

- User names `#N` to implement.
- User says *skip issue* / *just fix* (trivial).
- Question-only messages.

## Project constants

| Key | Value |
|-----|--------|
| Repo | `{{GH_REPO}}` |
| Project | `{{PROJECT_TITLE}}` — {{PROJECT_BOARD_URL}} |
| Scripts | `scripts/gh-triage-issue.sh`, `scripts/gh-close-verified-issue.sh` |

## Related

- `docs/github-workflow.md` — board & daily flow
- `docs/agent-platforms.md` — per-platform official setup
- `.workflow-kit.env` — repo config (generated by bootstrap)
